services :
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    volumes: 
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U user"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: backend_app
    restart: unless-stopped
    ports: 
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:${POSTGRES_PASSWORD}@db:5432/mydb
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
    driver: local